### ISSUE TITLE
Did you compare the critic model's performance with respect to automatically created critic data. 

### ISSUE THREAD

**Issue by debjitpaul** [facebookresearch/Shepherd#13]
Hi, 

Firstly really cool work. 

The following paper might be interesting for you: REFINER: Reasoning Feedback on Intermediate Representations https://arxiv.org/pdf/2304.01904.pdf 

Best regards,
Debjit

**Comment by tianlu-wang** [comment]
Definitely interested. Thanks for sharing!
________________________________
From: Debjit Paul ***@***.***>
Sent: Wednesday, August 23, 2023 12:02 AM
To: facebookresearch/Shepherd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [facebookresearch/Shepherd] Did you compare the critic model's performance with respect to automatically created critic data. (Issue #13)

Hi, Firstly really cool work. The following paper might be interesting for you: REFINER: Reasoning Feedback on Intermediate Representations https: //arxiv. org/pdf/2304. 01904. pdf Best regards, Debjit — Reply to this email directly, view
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender

ZjQcmQRYFpfptBannerEnd

Hi,

Firstly really cool work.

The following paper might be interesting for you: REFINER: Reasoning Feedback on Intermediate Representations https://arxiv.org/pdf/2304.01904.pdf<https://arxiv.org/pdf/2304.01904.pdf>

Best regards,
Debjit
